# Generated by Django 5.2.6 on 2025-09-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_foto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='miniatura_portada',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/miniaturas/'),
        ),
    ]
